============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-5.4.2, py-1.5.2, pluggy-0.13.1
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/ptisnovs/src/python/testing-in-python/pytest/average09
plugins: voluptuous-1.0.2, benchmark-3.2.3, cov-2.5.1
collected 14 items

test_average.py ....F..                                                  [ 50%]
test_average_2.py ....F..                                                [100%]

=================================== FAILURES ===================================
______________________ test_average_basic_3[values4-0.5] _______________________

values = (0, 10), expected = 0.5

    @pytest.mark.parametrize(
        "values,expected",
        [
            pytest.param(
                (1, 1), 1
            ),
            pytest.param(
                (1, 2), 1.5
            ),
            pytest.param(
                (0, 1), 0.5
            ),
            pytest.param(
                (1, 2, 3), 2.0
            ),
            pytest.param(
                (0, 10), 0.5
            ),
        ],
    )
    def test_average_basic_3(values, expected):
        """Otestování výpočtu průměru."""
        result = average(values)
>       assert result == expected, "Očekávaná hodnota {}, vráceno {}".format(expected, result)
E       AssertionError: Očekávaná hodnota 0.5, vráceno 5.0
E       assert 5.0 == 0.5

test_average.py:31: AssertionError
______________________ test_average_basic_3[values4-0.5] _______________________

values = (0, 10), expected = 0.5

    @pytest.mark.parametrize(
        "values,expected",
        (
            pytest.param(
                (1, 1), 1
            ),
            pytest.param(
                (1, 2), 1.5
            ),
            pytest.param(
                (0, 1), 0.5
            ),
            pytest.param(
                (1, 2, 3), 2.0
            ),
            pytest.param(
                (0, 10), 0.5
            ),
        ),
    )
    def test_average_basic_3(values, expected):
        """Otestování výpočtu průměru."""
        result = average(values)
>       assert result == expected, "Očekávaná hodnota {}, vráceno {}".format(expected, result)
E       AssertionError: Očekávaná hodnota 0.5, vráceno 5.0
E       assert 5.0 == 0.5

test_average_2.py:31: AssertionError

----------- coverage: platform linux, python 3.6.6-final-0 -----------
Name                Stmts   Miss  Cover
---------------------------------------
average.py              2      0   100%
main.py                 4      4     0%
test_average.py        13      0   100%
test_average_2.py      13      0   100%
---------------------------------------
TOTAL                  32      4    88%

=========================== short test summary info ============================
FAILED test_average.py::test_average_basic_3[values4-0.5] - AssertionError: O...
FAILED test_average_2.py::test_average_basic_3[values4-0.5] - AssertionError:...
========================= 2 failed, 12 passed in 0.08s =========================
